### ISSUE TITLE
Build: 404 page

### ISSUE THREAD

**Issue by plackyfantacky** [plackyfantacky/ariom-theme#10]

**Comment by plackyfantacky** [comment]
Build without the 404 3D text scene. ThreeJS Thingy isn't ready yet. Blocked by:

- [ ] plackyfantacky/threejs-thingy#3
- [ ] plackyfantacky/threejs-thingy#4
- [ ] plackyfantacky/ariom-theme/#21
